"""Formulates the genome assembly problem as a QUBO using the Singularity Optimisation Platform."""

import singularity.optimization_backend as sop

from use_case.read_compressed_graph import read_unitigs

MAX_VARIABLES = 5000


class Map_to_SOP:
    """
    This class defines the QUBO formulation based on the data structure of the unitigs generated by BCALM 2.
    It defines the binary variables, the constraints and builds the model using singularity.
    """

    def __init__(self, filepath, base_dir=None):
        self.unitigs, self.unconnected_unitigs = read_unitigs(filepath, base_dir=base_dir)
        self.model = sop.Model()
        self.breaking_nodes = {}
        self.variables = self.binary_variables(self.model)
        self.num_of_variables = len(self.variables)
        self.num_of_flow_conservation_constraint = None
        self.num_of_breaking_nodes_constraint = None
        self.num_of_sign_balance_constraint = None

    def binary_variables(self, model):
        """
        define binary variable for all edges"""
        variables = {}

        for k_mer, k_mer_attr in self.unitigs.items():
            node_from = k_mer
            outgoing_kmers = k_mer_attr.outgoing_nodes
            if len(outgoing_kmers) == 1:
                self.breaking_nodes[node_from] = 1
            else:
                self.breaking_nodes[node_from] = 0

            for k, value in outgoing_kmers.items():
                if len(variables) >= MAX_VARIABLES:
                    raise ValueError(
                        f"Graph exceeds the maximum of {MAX_VARIABLES} binary variables."
                    )
                node_to = int(k)
                from_sign = value["from_sign"]
                to_sign = value["to_sign"]
                variables[(node_from, node_to, from_sign, to_sign)] = model.add_variable(
                    name=f"{node_from}_{node_to}_{from_sign}_{to_sign}"
                )

        return variables

    def objective(self):
        return sum(self.variables.values())

    def flow_conservation_constraint(self):
        """Ensures that for each non-breaking node, exactly one incoming
        edge from a non-breaking node and one outgoing edge to a non-breaking node are selected.
        :return: A list containing the sop.Constraint
        """
        all_constraint = []
        for k_mer, k_mer_attr in self.unitigs.items():
            k_sum_incoming = []
            k_sum_outgoing = []

            connected_k_mers_incoming = k_mer_attr.incoming_nodes
            connected_k_mers_outgoing = k_mer_attr.outgoing_nodes

            if len(connected_k_mers_incoming) == 1 and len(connected_k_mers_outgoing) == 1:
                continue  # handled by breaking_nodes_constraint

            if len(connected_k_mers_incoming) > 1:
                for k, incoming_value in connected_k_mers_incoming.items():
                    if self.breaking_nodes[k] == 1:
                        continue
                    if incoming_value["to_sign"] == "+":
                        k_sum_incoming.append(
                            self.variables[(k, k_mer, incoming_value["from_sign"], "+")]
                        )
                    elif incoming_value["to_sign"] == "-":
                        k_sum_incoming.append(
                            self.variables[(k, k_mer, incoming_value["from_sign"], "-")]
                        )

            if len(connected_k_mers_outgoing) > 1:
                for k, outgoing_value in connected_k_mers_outgoing.items():
                    if self.breaking_nodes[k] == 1:
                        continue
                    if outgoing_value["from_sign"] == "+":
                        k_sum_outgoing.append(
                            self.variables[(k_mer, k, "+", outgoing_value["to_sign"])]
                        )
                    elif outgoing_value["from_sign"] == "-":
                        k_sum_outgoing.append(
                            self.variables[(k_mer, k, "-", outgoing_value["to_sign"])]
                        )

            if len(k_sum_outgoing) > 1:
                all_constraint.append(sum(k_sum_outgoing) == 1)

            if len(k_sum_incoming) > 1:
                all_constraint.append(sum(k_sum_incoming) == 1)

        self.num_of_flow_conservation_constraint = len(all_constraint)

        return all_constraint

    def breaking_nodes_constraint(self):
        """Ensures that for each breaking node (exactly one incoming and one outgoing edge),
        the combined sum of the selected incoming and outgoing edges equals 1.
        :return: A list containing the sop.Constraint
        """
        all_constraint = []
        for k_mer, k_mer_attr in self.unitigs.items():
            connected_k_mers_incoming = k_mer_attr.incoming_nodes
            connected_k_mers_outgoing = k_mer_attr.outgoing_nodes

            if len(connected_k_mers_incoming) == 1 and len(connected_k_mers_outgoing) == 1:
                k_sum_incoming = []
                k_sum_outgoing = []

                for k, outgoing_value in connected_k_mers_outgoing.items():
                    if outgoing_value["from_sign"] == "+":
                        k_sum_outgoing.append(
                            self.variables[(k_mer, k, "+", outgoing_value["to_sign"])]
                        )
                    elif outgoing_value["from_sign"] == "-":
                        k_sum_outgoing.append(
                            self.variables[(k_mer, k, "-", outgoing_value["to_sign"])]
                        )
                for k, incoming_value in connected_k_mers_incoming.items():
                    if incoming_value["to_sign"] == "+":
                        k_sum_incoming.append(
                            self.variables[(k, k_mer, incoming_value["from_sign"], "+")]
                        )
                    elif incoming_value["to_sign"] == "-":
                        k_sum_incoming.append(
                            self.variables[(k, k_mer, incoming_value["from_sign"], "-")]
                        )
                all_constraint.append(sum(k_sum_incoming + k_sum_outgoing) == 1)

        self.num_of_breaking_nodes_constraint = len(all_constraint)

        return all_constraint

    def sign_balance_constraint(self):
        """
        Ensures that for each non-breaking node, the number of incoming "+" edges equals the
        number of outgoing "+" edges, and the number of incoming "-" edges equals the number
        of outgoing "-" edges.
        :return: A list containing the sop.Constraint
        """

        all_constraint = []

        for k_mer, k_mer_attr in self.unitigs.items():
            if self.breaking_nodes[k_mer] == 1:
                continue
            incoming_k_mers = k_mer_attr.incoming_nodes
            outgoing_k_mers = k_mer_attr.outgoing_nodes
            incoming_plus = []
            outgoing_plus = []
            incoming_minus = []
            outgoing_minus = []

            for (k, incoming_value), (k2, outgoing_value) in zip(
                incoming_k_mers.items(), outgoing_k_mers.items()
            ):
                if self.breaking_nodes[k] == 1:
                    continue

                else:
                    if incoming_value["to_sign"] == "+":
                        incoming_plus.append(
                            self.variables[(k, k_mer, incoming_value["from_sign"], "+")]
                        )

                    if incoming_value["to_sign"] == "-":
                        incoming_minus.append(
                            self.variables[k, k_mer, incoming_value["from_sign"], "-"]
                        )

                if self.breaking_nodes[k2] == 1:
                    continue
                else:
                    if outgoing_value["from_sign"] == "-":
                        outgoing_minus.append(
                            self.variables[k_mer, k2, "-", outgoing_value["to_sign"]]
                        )

                    if outgoing_value["from_sign"] == "+":
                        outgoing_plus.append(
                            self.variables[k_mer, k2, "+", outgoing_value["to_sign"]]
                        )

            if len(incoming_plus) >= 1 and len(outgoing_plus) >= 1:
                all_constraint.append(sum(incoming_plus) == sum(outgoing_plus))

            if len(incoming_minus) >= 1 and len(outgoing_minus) >= 1:
                all_constraint.append(sum(incoming_minus) == sum(outgoing_minus))

        self.num_of_sign_balance_constraint = len(all_constraint)

        return all_constraint

    def num_of_constraints(self):
        """
        return the total number of constraints
        :return: int
        """
        if any(
            x is None
            for x in [
                self.num_of_flow_conservation_constraint,
                self.num_of_breaking_nodes_constraint,
                self.num_of_sign_balance_constraint,
            ]
        ):
            return None
        else:
            return (
                self.num_of_flow_conservation_constraint
                + self.num_of_breaking_nodes_constraint
                + self.num_of_sign_balance_constraint
            )

    def build_model(self, penalty=800):
        """
        This method builds the singularity model using the objective function
        and the constraints
        :param penalty: Penalty strength (α = β) applied to all constraints
        :return: sop.Model
        """

        try:
            model = self.model
            obj_expr = self.objective()
            flow_conservation = self.flow_conservation_constraint()
            breaking_nodes = self.breaking_nodes_constraint()
            sign_balance = self.sign_balance_constraint()

            if not flow_conservation and not breaking_nodes and not sign_balance:
                return None

            model.set_objective(obj_expr, sop.Sense.MINIMIZE)
            for c in flow_conservation + breaking_nodes + sign_balance:
                model.add_constraint(c, penalty)

            return model
        except Exception:
            return None
